version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    image: "mathewgeorge_docker_project_07may2021:${build_container_version}"
    stdin_open: true
    tty: true
    volumes:
      - .:/dockerProject

  docpush:
    build: .
    image: "gladiotuetur/mathewgeorge_docker_project_07may2021:${build_container_version}"  # goes to your repository on Docker Hub
